carapp/urls.py
from django.urls import path, include
from . import views
from .views import BuyerSignUpView

app_name = 'carapp'
urlpatterns = [
    path('', views.homepage, name='homepage'),  # HomePage.as_view()
    path('carapp/aboutus', views.aboutus, name='aboutus'),  # AboutUsView.as_view()
    path('carapp/<int:cartype_no>', views.cardetail, name='cardetail'),
    path('groupmembers/', views.GroupMemebers.as_view(), name='groupmembers'),  # views.groupmembers

    path('carapp/vehicles', views.vehicles, name='vehicles'),
    path('carapp/order', views.orderhere, name='order'),
    path('carapp/orderhere', views.orderhere, name='orderhere'),
    path('carapp/search', views.search, name='search'),

    path('signup/', BuyerSignUpView.as_view(), name='signup'),  # SignUpView
    path('accounts/', include('django.contrib.auth.urls')),  # accounts pages

    path('login/', views.login_here, name='login'),
    path('logout/', views.logout_here, name='logout'),

    path('myorders', views.list_of_orders, name='list_of_orders')
]

carsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carapp.urls')),
]

carapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class CarType(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return str(self.id) + " " + self.name


class Vehicle(models.Model):
    FEATURE_CHOICES = [('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface')
        , ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'),
                       ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'),
                       ('Reversing Camera', 'Reversing Camera'),
                       ('Auto Start / Stop', 'Auto Start / Stop')
                       ]
    car_type = models.ForeignKey(CarType, related_name='vehicles', on_delete=models.CASCADE)
    car_name = models.CharField(max_length=200)
    car_price = models.DecimalField(max_digits=10, decimal_places=6)
    inventory = models.PositiveIntegerField(default=10)
    instock = models.BooleanField(default=True)
    # added
    description = models.TextField(blank=True, default='', max_length=150)
    features = models.CharField(choices=FEATURE_CHOICES, max_length=100, default='Cruise Control')

    def __str__(self):
        return str(self.id) + " " + self.car_name + " " + self.car_type.name + " " + str(self.car_price) + " " + str(
            self.inventory)


class Buyer(User):
    AREA_CHOICES = [('W', 'Windsor'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington'),
                    ('TO', 'Toronto'), ('CH', 'Chatham'), ('WA', 'Waterloo')]
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    area = models.CharField(max_length=2, choices=AREA_CHOICES, default='CH')
    interested_in = models.ManyToManyField(CarType)
    # added
    phone_number = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} stays at {self.shipping_address} {self.area}"


class OrderVehicle(models.Model):
    vehicle = models.ForeignKey(Vehicle, related_name='orders', on_delete=models.CASCADE)
    buyer = models.ForeignKey(Buyer, related_name='orders', on_delete=models.CASCADE)
    # number of vehicles being ordered
    quantity = models.PositiveIntegerField(default=0)
    STATUS_CHOICES = [
        (0, 'cancelled'),
        (1, 'placed'),
        (2, 'shipped'),
        (3, 'delivered'),
        (4, 'successful')
    ]
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.vehicle.car_name} ordered by {self.buyer.first_name} on {self.last_updated}"

    def total_price(self):
        return self.quantity * self.vehicle.car_price


class GroupMember(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    semester = models.IntegerField()
    link = models.URLField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name} semester {self.semester}"

    class Meta:
        ordering = ['first_name']

carapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from carapp.models import OrderVehicle, Vehicle, Buyer


class OrderVehicleForm(forms.ModelForm):
    class Meta:
        model = OrderVehicle
        fields = ['vehicle', 'buyer', 'quantity']  # vehicle_ordered
        widgets = {'buyer': forms.Select}
        labels = {'quantity': 'Vehicles Ordered'}  # Written this way to check it on the page


class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    subject = forms.CharField(max_length=30)  # widget=forms.TextInput(attrs={''})
    message = forms.CharField(widget=forms.Textarea)


class VehicleSearchForm(forms.Form):
    id = forms.IntegerField()


class BuyerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Buyer
        fields = ('username', 'email', 'phone_number', 'shipping_address')

carapp/views.py
# Import necessary classes
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect

from .forms import VehicleSearchForm, OrderVehicleForm, BuyerSignUpForm  # ContactUsForm
from .models import CarType, Vehicle, GroupMember, Buyer, OrderVehicle
from django.shortcuts import get_object_or_404
from django.views import View
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy


def homepage(request):
    visits = request.session.get('home_page_visit', 0)
    if visits is None:
        request.session['home_page_visit'] = 0
    else:
        visits += 1
        request.session['home_page_visit'] = visits

    cookie_value = request.COOKIES.get('home_page_visit', f'This is a default value')

    vehicles = Vehicle.objects.all().order_by('-car_price')
    context = {'vehicles': vehicles, 'heading1': 'Different Types of Cars', 'visits': visits,
               'cookie_value': cookie_value}
    response = render(request, 'carapp/homepage.html', context)
    response.set_cookie('home_page_visit', f'Old session value {visits}', max_age=3600, secure=True)
    return response

class HomePage(View):

    def get(self, request):
        cartype_list = Vehicle.objects.all().order_by('-car_price')[:10]
        response = HttpResponse()
        heading1 = '<p>' + 'Different Types of Cars: ' + ' < / p > '
        response.write(heading1)
        for cartype in cartype_list:
            para = '<p>' + str(cartype.id) + ': ' + str(cartype) + '</p>'
            response.write(para)
        return response


def aboutus(request):
    return render(request, 'carapp/aboutus.html')


def cardetail(request, cartype_no):
    car_type = get_object_or_404(CarType, pk=cartype_no)
    cars = Vehicle.objects.filter(car_type_id=cartype_no)
    context = {'cars': cars, 'cartype_no': cartype_no, 'cartype_name': car_type.name}
    return render(request, 'carapp/cardetail.html', context)


def vehicles(request):
    all_vehicles = Vehicle.objects.all()
    context = {'vehicles': all_vehicles}
    return render(request, 'carapp/vehicles.html', context)


def groupmembers(request):
    response = HttpResponse()
    members = GroupMember.objects.all().order_by('first_name')
    heading1 = '<p>' + f'Group members are : ' + ' </p> '
    response = HttpResponse()
    response.write(heading1)
    for member in members:
        para = '<p>' + f'{member.first_name} {member.last_name} semester: {member.semester} <a href="{member.link}"> Link </a>' + '</p>'
        response.write(para)
    return response


# class GroupMembers(View):
# do it in 3 ways, using the Model and not using the model

# 1)
class GroupMemebers(View):
    # model = GroupMember
    # template_name = 'carapp\\groupmembers.html'
    # context_object_name = 'groupmembers'

    def get(self, request):
        members = GroupMember.objects.all().order_by('first_name')
        return render(request, 'carapp/groupmembers.html', {'members': members})


class AboutUsView(View):

    def get(self, request):
        response = HttpResponse()
        response.write("<h3>This is a Car Showroom </h3>")
        return response


# def contactusview(request):
# data = {'name': 'Iverique'}
# form = ContactUsForm(data) #Can be empty inially
# form = ContactUsForm(request.POST)  #to bind data, populate it with submitted data
# return "render(request, template, context)"


def search(request):
    form = VehicleSearchForm(request.GET)
    vehicles = Vehicle.objects.all()

    if form.is_bound and form.is_valid:  # Checking if form is valid
        if 'id' in form.data:
            id = form.data['id']
            vehicle = get_object_or_404(Vehicle, pk=id)  # Retrieving vehicle by primary key
            return render(request, "carapp/search_vehicle.html", {'found': vehicle, 'vehicles': vehicles})

    return render(request, "carapp/search_vehicle.html", {'vehicles': vehicles})


def orderhere(request):
    msg = ''
    vehiclelist = Vehicle.objects.all()
    if request.method == 'POST':
        form = OrderVehicleForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            # if order.vehicle.orders <= order.vehicle.instock:
            # if order.vehicle.orders.count() <= order.vehicle.inventory:
            if order.quantity <= order.vehicle.inventory:
                order.vehicle.inventory -= order.quantity  # order.quantity
                order.vehicle.save()
                order.save()
                msg = 'Your vehicle has been ordered'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
                return render(request, 'carapp/nosuccess_order.html', {'msg': msg})
    else:
        form = OrderVehicleForm()
    return render(request, 'carapp/orderhere.html', {'form': form, 'msg': msg, 'vehiclelist': vehiclelist})


class SignUpView(CreateView):
    form_class = UserCreationForm
    # this is not working well
    success_url = reverse_lazy("carapp:login")  # for class based, instead of  reverse('carapp:login')
    template_name = 'carapp/signup.html'


class BuyerSignUpView(CreateView):
    form_class = BuyerSignUpForm
    success_url = reverse_lazy('carapp:login')
    template_name = 'carapp/signup.html'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_buyer = True
        user.save()
        return super().form_valid(form)


# Create your views here.
def login_here(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('carapp:homepage'))
            else:
                return HttpResponse('Your account is disabled')
        else:
            return HttpResponse('Login details are incorrect')
    else:
        return render(request, 'carapp/login_here.html')


@login_required
def logout_here(request):
    logout(request)
    # return HttpResponseRedirect(reverse('carapp:homepage'))
    return HttpResponseRedirect('/')


@login_required
def list_of_orders(request):
    print("User getting all orders")

    is_user_buyer = hasattr(request.user, 'buyer')
    if is_user_buyer:
        orders = OrderVehicle.objects.filter(buyer=request.user.buyer)
        context = {'orders': orders, 'is_user_buyer': is_user_buyer}
        return render(request, 'carapp/list_of_orders.html', context)
    else:
        return render(request, 'carapp/list_of_orders.html', {'orders': [], 'is_user_buyer': False})

carapp/templates/carapp/aboutus.html
{%extends 'carapp/base.html'   %}
{% block body_block %}

<h3>This is a Car Showroom </h3>

{% endblock %}

carapp/templates/carapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'carapp/style.css' %}"/>
    <title> CarSite - {% block title %} Welcome! {% endblock %}</title>
</head>
<body>
<div style="min-height: 70vh">
    <h1>{% block myhdg %} Welcome to our online car store {% endblock %}</h1>
    {% block body_block %} {% endblock %}
</div>
<div>
    <ul>
        <li class="hbar1"><a href="{% url 'carapp:aboutus' %}"> Find out about this site </a><br/></li>
        <li class="hbar1"><a href = "{% url 'carapp:homepage'%}"> Click here to return to the home page </a><br/></li>
         <li class="hbar1"><a href = "{% url 'carapp:vehicles'%}"> Click here to see vehicles </a></li>

    </ul>
</div>
</body>

carapp/templates/carapp/cardetail.html
{% extends 'carapp/base.html' %}

{% block body_block %}


<p> Following are the Vehicles in {{cartype_name}} with Cartype No {{cartype_no }}:</p>
{% if cars %}
<h2> Type of Cars </h2>
<ul>
	{% for car in cars %}
<li> {{ car.car_name}} </li>
{% endfor %}
</ul>
{% else %}
<strong> None of the car types is available! </strong>
{% endif %}
{% endblock %}

carapp/templates/carapp/groupmembers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div>
    <h3> Group members</h3>

    {% for member in members %}

        <div>
           <p>{{ member.first_name }} </p>
            <p> {{ member.last_name }}</p>
            <p> Semester: {{ member.semester }} </p>
        <p> <a href="{{ member.link }}"> {{ member.link }} </a></p>

        </div>
    {% endfor %}
</div>

</body>
</html>

carapp/templates/carapp/homepage.html
{% extends 'carapp/base.html' %}
{% load static %}

{% block body_block %}
<div>
    <a href="{% url 'carapp:aboutus' %}">About Us</a>
    &nbsp;|&nbsp;
    <a href="{% url 'carapp:search' %}">Search</a>
    &nbsp;|&nbsp;
    <a href="{% url 'carapp:groupmembers' %}">Team Details</a>
     |
{% if user.is_authenticated %}
    <a href="{% url 'carapp:list_of_orders' %}">My Orders</a>
    |
  <span> User: {{ user.username }} </span>  <a href = "{% url 'carapp:logout'%}"> Logout</a>
{% else %}
    <a href = "{% url 'carapp:login'%}"> Login</a>
        {%  endif%}
</div>
    <h3> Vehicles session count: {{ visits }} cookie: {{ cookie_value }} </h3>

<div>
<div><h5> Ferrari</h5><img src="{% static 'images/ferrai.jpg' %}" alt="Ferrari"></div>
<div><h5> Lambo</h5> <img src="{% static 'images/lambo.webp' %}" alt="Lambo"></div>
</div>
{% endblock %}

carapp/templates/carapp/list_of_orders.html
{% extends 'carapp/base.html' %}

{% block body_block %}
    <h4>My orders</h4>
{% if is_user_buyer %}
<ul>
{% for o in orders %} <li> {{ o.vehicle.car_name }} {{ o.vehicle.car_type }}
     Quantity: {{ o.quantity }} Total Price : {{ o.total_price |floatformat:2 }} </li>  {% endfor %}
</ul>
{% else %}
    <p>You are not registered </p>
{% endif %}

{% endblock %}

carapp/templates/carapp/login_here.html
{% extends 'carapp/base.html' %}

{% block body_block %}

    <form method="post" action="{% url 'carapp:login' %}"> {% csrf_token %}
    <div>
         <input type="text" name="username" placeholder="Enter username" />
    </div>
     <div>
         <input type="password" name="password" placeholder="Enter password" />
    </div>

      <div>
          <input type="submit" value="Sign in here">
      </div>
    </form>
{% endblock %}

carapp/templates/carapp/nosuccess_order.html
{% extends 'carapp/base.html' %}

{% block body_block %}

<h3> No success order</h3>
    {% if msg %} <p> {{ msg }}</p> {% endif %}
{% endblock %}

carapp/templates/carapp/orderhere.html
{% extends 'carapp/base.html' %}

{% block body_block %}

<h3> You can place your order here.</h3>

{% if vehiclelist %}
<h2> Type of Cars </h2>
<ol>
	{% for car in vehiclelist %}

<li> <p> {{car.car_name  }} {{ car.car_price | floatformat:2 }}</p>   </li>
{% endfor %}
</ol>
{% else %}
<strong> None of the car types is available! </strong>
{% endif %}

    <form method="post" action="{% url 'carapp:orderhere' %}" >
    {% csrf_token %}
    <table>{{ form.as_table }} </table>
    <input value="submit" type="submit">
    </form>

{% endblock %}

carapp/templates/carapp/search_vehicle.html
{% extends 'carapp/base.html' %}

{% block body_block %}

<div>
<form method="GET" action="{% url 'carapp:search' %}">
     <label>
        Select Vehicle
        <select name="id">
            {% for vehicle in vehicles %}
            <option value="{{vehicle.id }}" {% if found and vehicle.id == found.id %} selected {% endif %}> {{ vehicle.car_name }}</option>
            {% endfor %}
        </select>
    </label>
  <input type="submit" value="Filter Cars" />

</form>
{% if found %}
    <h4>Your search result {{ found.car_price |floatformat:2 }}</h4>
{% endif %}

</div>

{% endblock %}

carapp/templates/carapp/signup.html
{% extends 'carapp/base.html' %}

{% block body_block %}
  <h2>Sign Up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}

carapp/templates/carapp/vehicles.html
{% extends 'carapp/base.html' %}

{%  block body_block %}
   <h1>All Vehicles</h1>
  {% if vehicles|length > 1 %}
    <ul>

    {% for vehicle in vehicles %}
    <li>  {{ vehicle.car_name }} </li>
    {% endfor %}
    </ul>
  {% else %}
      <p> There are no vehicles</p>
   {% endif %}

     <a href="{% url 'carapp:order' %}" > Order Here </a>
{% endblock %}